### ISSUE TITLE
Problem with running TypeScript Feature Viewer

### ISSUE THREAD

**Issue by n-szulc** [BioComputingUP/FeatureViewerTypeScript#23]
Hello

I have a problem running the TypeScript Feature Viewer.
I installed it via npm: npm install feature-viewer-typescript

The error I encounter is in import:
Uncaught SyntaxError: Cannot use import statement outside a module

I am not an expert in javascript and have been following the steps described in Readme. I attach a minimal HTML (saved as txt for issue import) in which I cannot get it running; the path to feature-viewer-typescript/lib is correct on my computer. I would be most grateful for the instructions how to set it.

Best regards,

[visualize_features.txt](https://github.com/BioComputingUP/feature-viewer-typescript/files/8349151/visualize_features.txt)

**Comment by Lisanna** [comment]
Hello! 
In the documentation [here](http://old.protein.bio.unipd.it/feature-viewer/) we included an example of HTML initialisation. As you may see from there, the import statement is different in simple HTML, as it is done with:
`<script src="./dist/feature-viewer-webpack.bundle.js"></script>` 

Could you test it in your setting and check if this works?

**Comment by n-szulc** [comment]
Hi,

thank you very much for your reply, after doing `npm install feature-viewer-typescript` I have no dist directory in the node_modules/feature-viewer-typescript and also no node_modules/feature-viewer-typescript/dist/feature-viewer-webpack.bundle.js

Could I ask for a step-by-step instruction regarding Feature Viewer (Typescript version) installation and also a minimal working example HTML file?
I am really interested in applying the Feature Viewer it in my tool.

**Comment by mb925** [comment]
Good morning,

thank you for your interest in the library, your comments have been helpful! 

I attached an example of working html in this answer. If you try it out, let me know if everything works fine. The bundle.js file I am using is now available on Github under the dist folder.

These days the library is undergoing some changes, thank you for your patience. 
I'm available for any other issue you may run into.

[fv-test.tar.gz](https://github.com/BioComputingUP/FeatureViewerTypeScript/files/8425862/fv-test.tar.gz)

**Comment by n-szulc** [comment]
Hello,

thank you very much for your reply and help! Everything is working now. 
One minor suggestion, the bottom sequence position panel seems to be slightly cropped (please see the attached screen).

Best regards and thank you once again

<img width="1582" alt="fv_screen" src="https://user-images.githubusercontent.com/30737090/161990942-c9ff8964-698f-41dd-9017-7583a672b2dd.png">

**Comment by n-szulc** [comment]
I do not know whether you would be interested in further feedback, but I started using the Typescript Feature Viewer in my currently developed web server, I am impressed how easy and powerful it is, but surely I would have some suggestions on possible improvements.

**Comment by mb925** [comment]
I took note of the sequence position panel being cropped, that I will fix for sure in the next versions of the tool. As well as the flags that are slightly misaligned and other issues.
Nonetheless, any additional suggestion is highly appreciated and will be considered for the implementation, so feel free to send in your comments. 
Thank you.
