### ISSUE TITLE
Disappearing labels

### ISSUE THREAD

**Issue by n-szulc** [BioComputingUP/FeatureViewerTypeScript#24]
Hi,

once again, big thanks for helping me with installation, I managed to successfully start using the Typescript Feature Viewer!

I have two critical requests regarding the release of my web server in the Internet:
- cropped text in the X asis
- disappearing labels

@mb925 could you please contact me on priv? I would send you screens from my unpublished tool regarding the labels issue and provide you more details as well as other suggestions.

Best regards

**Comment by mb925** [comment]
Sure, I contacted you by email.

Martina

**Comment by n-szulc** [comment]
Thanks, I just replied, if you did not receive it (I had a problem with the attachment) please let me know.
