### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by remimestdagh** [BioComputingUP/FeatureViewerTypeScript#25]
Hi repo owners,

I started using this package in my React application. I noticed some issues regarding the interfaces.ts file.
![image](https://user-images.githubusercontent.com/47556303/185885379-fbcf4b6b-f0bc-4137-b049-b84e0304c013.png)

On the master branch 'data' has been updated to be an array of FeatureData. Which is perfect. The current release still has it as a string.

My question: when will this be released so I can update the package?

Kind regards
Remi

**Comment by mb925** [comment]
Hello,

Thank you for your feedback and interest. We are considering a new release, I will have to check if everything is actually ready and I will then proceed with it. If there are no issues I hope to do it in the next few days.
I will get back to you and update you about it.

Best,
Martina

**Comment by mb925** [comment]
Hello,

I have now released a new version. If you stumble in any problem let me know.
Have a nice day,

Martina
